version: '3.8'
services:
  postgres:
    container_name: pg_db
    image: postgres:alpine
    restart: unless-stopped
    ports:
      - 5433:5433
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      net:
        ipv4_address: 172.16.0.3

  # server:
  #   container_name: internship_server
  #   restart: unless-stopped
  #   build:
  #     context: server
  #   ports:
  #     - '5001:5001'
  #   depends_on:
  #     - postgres
  #   volumes:
  #     - media:/usr/src/server/media
  #   networks:
  #     net:
  #       ipv4_address: 172.16.0.2

volumes:
  pgdata:
  media:

networks:
  net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.0.0/23
    driver_opts:
      com.docker.network.bridge.name: common-bridge2
